0:
  ref_sensor_ids:
  - 48176
  - 48177
  source: logfile_auto_detection
1:
  ref_sensor_ids:
  - 48176
  - 48177
  source: logfile_auto_detection
2:
  ref_sensor_ids:
  - 48176
  - 48177
  source: logfile_auto_detection
3:
  ref_sensor_ids:
  - 48176
  - 48177
  source: logfile_auto_detection
4:
  ref_sensor_ids:
  - 48176
  - 48177
  source: logfile_auto_detection
5:
  ref_sensor_ids:
  - 48176
  - 48177
  source: logfile_auto_detection
6:
  ref_sensor_ids:
  - 48177
  - 48421
  source: logfile_auto_detection
7:
  ref_sensor_ids:
  - 48177
  - 48421
  source: logfile_auto_detection
8:
  ref_sensor_ids:
  - 48177
  - 48421
  source: logfile_auto_detection
9:
  ref_sensor_ids:
  - 48421
  - 48422
  source: logfile_auto_detection
10:
  ref_sensor_ids:
  - 48421
  - 48422
  source: logfile_auto_detection
11:
  ref_sensor_ids:
  - 48421
  - 48422
  source: logfile_auto_detection
12:
  ref_sensor_ids:
  - 48422
  - 49215
  source: logfile_auto_detection
13:
  ref_sensor_ids:
  - 48422
  - 49215
  source: logfile_auto_detection
14:
  ref_sensor_ids:
  - 48422
  - 49215
  source: logfile_auto_detection
15:
  ref_sensor_ids:
  - 49215
  - 49262
  source: logfile_auto_detection
16:
  ref_sensor_ids:
  - 49215
  - 49262
  source: logfile_auto_detection
17:
  ref_sensor_ids:
  - 49215
  - 49262
  source: logfile_auto_detection
18:
  ref_sensor_ids:
  - 49262
  - 49263
  source: logfile_auto_detection
19:
  ref_sensor_ids:
  - 49262
  - 49263
  source: logfile_auto_detection
20:
  ref_sensor_ids:
  - 49262
  - 49263
  source: logfile_auto_detection
21:
  ref_sensor_ids:
  - 49263
  - 49264
  source: logfile_auto_detection
22:
  ref_sensor_ids:
  - 49263
  - 49264
  source: logfile_auto_detection
23:
  ref_sensor_ids:
  - 49263
  - 49264
  source: logfile_auto_detection
24:
  ref_sensor_ids:
  - 49264
  - 49265
  source: logfile_auto_detection
25:
  ref_sensor_ids:
  - 49264
  - 49265
  source: logfile_auto_detection
26:
  ref_sensor_ids:
  - 49264
  - 49265
  source: logfile_auto_detection
27:
  ref_sensor_ids:
  - 49265
  - 55174
  source: logfile_auto_detection
28:
  ref_sensor_ids:
  - 49265
  - 55174
  source: logfile_auto_detection
29:
  ref_sensor_ids:
  - 49265
  - 55174
  source: logfile_auto_detection
30:
  ref_sensor_ids:
  - 49317
  - 55174
  source: logfile_auto_detection
31:
  ref_sensor_ids:
  - 49265
  - 55174
  source: logfile_auto_detection
32:
  ref_sensor_ids:
  - 49265
  - 55174
  source: logfile_auto_detection
33:
  ref_sensor_ids:
  - 49317
  - 49318
  source: logfile_auto_detection
34:
  ref_sensor_ids:
  - 49317
  - 49318
  source: logfile_auto_detection
35:
  ref_sensor_ids:
  - 49317
  - 49318
  source: logfile_auto_detection
36:
  ref_sensor_ids:
  - 48176
  - 49318
  source: logfile_auto_detection
37:
  ref_sensor_ids:
  - 48176
  - 49318
  source: logfile_auto_detection
38:
  ref_sensor_ids:
  - 48176
  - 49318
  source: logfile_auto_detection
39:
  ref_sensor_ids:
  - 48176
  - 48422
  source: logfile_auto_detection
40:
  ref_sensor_ids:
  - 48176
  - 48422
  source: logfile_auto_detection
41:
  ref_sensor_ids:
  - 48176
  - 48422
  source: logfile_auto_detection
42:
  ref_sensor_ids:
  - 48422
  - 49263
  source: logfile_auto_detection
43:
  ref_sensor_ids:
  - 48422
  - 49263
  source: logfile_auto_detection
44:
  ref_sensor_ids:
  - 48422
  - 49263
  source: logfile_auto_detection
45:
  ref_sensor_ids:
  - 49263
  - 55174
  source: logfile_auto_detection
46:
  ref_sensor_ids:
  - 49262
  - 49263
  source: logfile_auto_detection
47:
  ref_sensor_ids:
  - 48177
  - 49262
  source: logfile_auto_detection
48:
  ref_sensor_ids:
  - 48177
  - 49262
  source: logfile_auto_detection
49:
  ref_sensor_ids:
  - 48177
  - 49262
  source: logfile_auto_detection
50:
  ref_sensor_ids:
  - 48177
  - 49262
  source: logfile_auto_detection
51:
  ref_sensor_ids:
  - 48177
  - 49262
  source: logfile_auto_detection
52:
  ref_sensor_ids:
  - 48177
  - 48421
  source: logfile_auto_detection
53:
  ref_sensor_ids:
  - 48177
  - 48421
  source: logfile_auto_detection
54:
  ref_sensor_ids:
  - 48177
  - 48421
  source: logfile_auto_detection
55:
  ref_sensor_ids:
  - 48177
  - 48421
  source: logfile_auto_detection
57:
  ref_sensor_ids:
  - 48177
  - 48421
  source: logfile_auto_detection
58:
  ref_sensor_ids:
  - 1003
  - 1004
  source: logfile_auto_detection
59:
  ref_sensor_ids:
  - 48177
  - 49264
  source: logfile_auto_detection
60:
  ref_sensor_ids:
  - 49264
  - 49265
  source: logfile_auto_detection
